In [1]:
import pandas as pd
import pandas_ta as ta
from sklearn.ensemble import RandomForestClassifier
import numpy as np
csv = "data/apr2_1h_30k.csv"
info = pd.read_csv(csv, parse_dates = ["Date"], index_col = "Date").dropna()

In [4]:
# Paso 1: Calculamos las estrategias y nuestra posición objetivo
# Nota: que varios indicadores tienen espacios vacíos
info.ta.strategy()

0it [00:00, ?it/s]/home/mauricio/anaconda3/lib/python3.9/multiprocessing/pool.py:48: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  return list(map(*args))
131it [01:06,  1.98it/s]

,Open,High,Low,Close,Volume,Quote Asset Volume,Number of Trades,Taker Buy Base Asset Volume,Taker Buy Quote Asset Volume,ABER_ZG_5_15,...,VIDYA_14,VTXP_14,VTXM_14,VWAP_D,VWMA_10,WCP,WILLR_14,WMA_10,ZL_EMA_10,ZS_30
Date,,,,,,,,,,,,,,,,,,,,,
2019-10-31 04:00:00,9102.15,9116.67,9074.42,9082.01,166462.385,1.513918e+09,5557,103636.894,9.425671e+08,NaN,...,NaN,NaN,NaN,9091.033333,NaN,9088.7775,NaN,NaN,NaN,NaN
2019-10-31 05:00:00,9084.35,9180.61,9078.55,9167.46,167313.515,1.527731e+09,5594,98623.844,9.006525e+08,NaN,...,NaN,NaN,NaN,9116.685246,NaN,9148.5200,NaN,NaN,NaN,NaN
2019-10-31 06:00:00,9167.46,9206.14,9094.56,9121.55,173418.026,1.585834e+09,5824,106021.800,9.694261e+08,NaN,...,NaN,NaN,NaN,9124.913385,NaN,9135.9500,NaN,NaN,NaN,NaN
2019-10-31 07:00:00,9120.50,9123.05,9074.68,9098.83,162489.166,1.478420e+09,5487,97821.853,8.900407e+08,NaN,...,NaN,NaN,NaN,9118.590281,NaN,9098.8475,NaN,NaN,NaN,NaN
2019-10-31 08:00:00,9098.24,9135.55,9076.89,9112.13,164301.111,1.496384e+09,7416,100965.855,9.195821e+08,9116.206667,...,NaN,NaN,NaN,9116.541348,NaN,9109.1750,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-04-02 23:00:00,28150.00,28350.00,28068.40,28197.90,5663.442,1.597356e+08,4488,2918.842,8.246372e+07,28078.546667,...,28227.222774,0.898973,1.049276,28272.682531,28122.929904,28203.5500,-43.150563,28110.805454,28118.273507,-0.748958
2023-04-03 00:00:00,28171.80,28350.00,28065.30,28177.80,4036.373,1.136892e+08,3223,2410.271,6.794765e+07,28117.380000,...,28225.959483,0.909472,1.028449,28197.700000,28108.405180,28192.7250,-43.586833,28120.563636,28146.060142,-0.831357
2023-04-03 01:00:00,28177.80,28500.00,27400.00,27930.80,6229.230,1.745319e+08,6454,3242.966,9.124217e+07,28096.433333,...,28212.215632,0.780588,0.977868,28043.510583,28089.605642,27940.4000,-51.745455,28087.178182,28091.558298,-2.173233
2023-04-03 02:00:00,27930.80,28100.00,27703.30,27978.00,4688.719,1.309303e+08,7120,2358.172,6.606630e+07,28072.166667,...,28204.745730,0.882255,1.062963,28007.011669,28077.494406,27939.8250,-47.454545,28065.809091,28039.638608,-1.725117
2023-04-03 03:00:00,27978.00,28096.00,27723.00,27925.70,3605.393,1.007235e+08,4386,2032.324,5.698027e+07,28037.746667,...,28194.038449,0.920601,1.055379,27989.118142,28052.715420,27917.6000,-52.209091,28037.438182,27969.431588,-1.851784

In [58]:
info['Target'] = (info['Close'] >= info['Open']).astype(int)
info

,Open,High,Low,Close,Volume,Quote Asset Volume,Number of Trades,Taker Buy Base Asset Volume,Taker Buy Quote Asset Volume,ABER_ZG_5_15,...,VTXP_14,VTXM_14,VWAP_D,VWMA_10,WCP,WILLR_14,WMA_10,ZL_EMA_10,ZS_30,Target
Date,,,,,,,,,,,,,,,,,,,,,
2019-10-31 04:00:00,9102.15,9116.67,9074.42,9082.01,166462.385,1.513918e+09,5557,103636.894,9.425671e+08,NaN,...,NaN,NaN,9091.033333,NaN,9088.7775,NaN,NaN,NaN,NaN,0
2019-10-31 05:00:00,9084.35,9180.61,9078.55,9167.46,167313.515,1.527731e+09,5594,98623.844,9.006525e+08,NaN,...,NaN,NaN,9116.685246,NaN,9148.5200,NaN,NaN,NaN,NaN,1
2019-10-31 06:00:00,9167.46,9206.14,9094.56,9121.55,173418.026,1.585834e+09,5824,106021.800,9.694261e+08,NaN,...,NaN,NaN,9124.913385,NaN,9135.9500,NaN,NaN,NaN,NaN,0
2019-10-31 07:00:00,9120.50,9123.05,9074.68,9098.83,162489.166,1.478420e+09,5487,97821.853,8.900407e+08,NaN,...,NaN,NaN,9118.590281,NaN,9098.8475,NaN,NaN,NaN,NaN,0
2019-10-31 08:00:00,9098.24,9135.55,9076.89,9112.13,164301.111,1.496384e+09,7416,100965.855,9.195821e+08,9116.206667,...,NaN,NaN,9116.541348,NaN,9109.1750,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-04-02 23:00:00,28150.00,28350.00,28068.40,28197.90,5663.442,1.597356e+08,4488,2918.842,8.246372e+07,28078.546667,...,0.898973,1.049276,28272.682531,28122.929904,28203.5500,-43.150563,28110.805454,28118.273507,-0.748958,1
2023-04-03 00:00:00,28171.80,28350.00,28065.30,28177.80,4036.373,1.136892e+08,3223,2410.271,6.794765e+07,28117.380000,...,0.909472,1.028449,28197.700000,28108.405180,28192.7250,-43.586833,28120.563636,28146.060142,-0.831357,1
2023-04-03 01:00:00,28177.80,28500.00,27400.00,27930.80,6229.230,1.745319e+08,6454,3242.966,9.124217e+07,28096.433333,...,0.780588,0.977868,28043.510583,28089.605642,27940.4000,-51.745455,28087.178182,28091.558298,-2.173233,0
2023-04-03 02:00:00,27930.80,28100.00,27703.30,27978.00,4688.719,1.309303e+08,7120,2358.172,6.606630e+07,28072.166667,...,0.882255,1.062963,28007.011669,28077.494406,27939.8250,-47.454545,28065.809091,28039.638608,-1.725117,1
2023-04-03 03:00:00,27978.00,28096.00,27723.00,27925.70,3605.393,1.007235e+08,4386,2032.324,5.698027e+07,28037.746667,...,0.920601,1.055379,27989.118142,28052.715420,27917.6000,-52.209091,28037.438182,27969.431588,-1.851784,0

In [16]:
# Paso 2: Calculamos la matriz de correlación
# Nota: Los valores vacíos no se toman en cuenta en el cálculo de la matriz
# Note que algunos valores están vacíos, esto no supone un problema
correlation_matrix = info.corr()
correlation_matrix

,Open,High,Low,Close,Volume,Quote Asset Volume,Number of Trades,Taker Buy Base Asset Volume,Taker Buy Quote Asset Volume,ABER_ZG_5_15,...,VIDYA_14,VTXP_14,VTXM_14,VWAP_D,VWMA_10,WCP,WILLR_14,WMA_10,ZL_EMA_10,ZS_30
Open,1.000000,0.684457,0.984294,0.980452,-0.192338,0.231084,-0.034325,-0.177299,0.266470,0.946745,...,0.981056,0.010693,-0.018128,0.952770,0.985186,0.956871,0.053778,0.991727,0.990259,0.001401
High,0.684457,1.000000,0.640239,0.690938,-0.140925,0.129768,-0.028519,-0.131417,0.153434,0.843437,...,0.699155,0.005417,-0.019562,0.762296,0.691572,0.850330,-0.016940,0.695724,0.695647,0.010924
Low,0.984294,0.640239,1.000000,0.972637,-0.187920,0.242797,-0.032211,-0.172898,0.278298,0.927312,...,0.976826,0.012590,-0.017112,0.942923,0.980349,0.940670,0.056898,0.983296,0.979880,0.004824
Close,0.980452,0.690938,0.972637,1.000000,-0.192126,0.225322,-0.034947,-0.177344,0.260492,0.942745,...,0.975173,0.010579,-0.018952,0.948025,0.977731,0.965971,0.077677,0.987785,0.991710,0.030765
Volume,-0.192338,-0.140925,-0.187920,-0.192126,1.000000,0.827140,0.184190,0.991122,0.795642,-0.187794,...,-0.196210,-0.004210,-0.001435,-0.189766,-0.193332,-0.188815,0.027239,-0.194024,-0.193366,-0.002184
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WCP,0.956871,0.850330,0.940670,0.965971,-0.188815,0.213781,-0.034932,-0.174641,0.247828,0.983083,...,0.957931,0.010071,-0.020353,0.959831,0.957230,1.000000,0.044915,0.964315,0.965393,0.020043
WILLR_14,0.053778,-0.016940,0.056898,0.077677,0.027239,0.051131,-0.000889,0.028569,0.054432,0.018529,...,0.013456,0.038373,-0.031175,0.012317,0.039645,0.044915,1.000000,0.046129,0.059018,0.590151
WMA_10,0.991727,0.695724,0.983296,0.987785,-0.194024,0.229271,-0.035160,-0.178835,0.264822,0.955777,...,0.989844,0.010097,-0.017979,0.960323,0.990809,0.964315,0.046129,1.000000,0.997156,-0.002474
ZL_EMA_10,0.990259,0.695647,0.979880,0.991710,-0.193366,0.227332,-0.035132,-0.178234,0.262721,0.952525,...,0.983933,0.010554,-0.018797,0.955880,0.985584,0.965393,0.059018,0.997156,1.000000,0.012167
ZS_30,0.001401,0.010924,0.004824,0.030765,-0.002184,-0.013023,-0.003323,-0.002710,-0.011203,-0.002390,...,-0.027232,0.050257,-0.055319,-0.012750,-0.009624,0.020043,0.590151,-0.002474,0.012167,1.000000

In [51]:
# Paso 3: Eliminamos indicadores altamente correlacionados
threshold = 0.7  # umbral de correlación
correlated_features = set()
for i in range(len(correlation_matrix.columns)):
    for j in range(i):
        if abs(correlation_matrix.iloc[i, j]) > threshold:
            colname = correlation_matrix.columns[i]
            correlated_features.add(colname)
            break

relevant_indicators = info.drop(correlated_features, axis=1, inplace=False)
relevant_indicators

,Open,High,Volume,Number of Trades,AD,ADOSC_3_10,ADX_14,DMN_14,AMATe_LR_8_21_2,AO_5_34,...,STC_10_12_26_0.5,SUPERTd_7_3.0,THERMO_20_2_0.5,THERMOl_20_2_0.5,THERMOs_20_2_0.5,TRIX_30_9,TTM_TRND_6,VHF_28,VTXP_14,VTXM_14
Date,,,,,,,,,,,,,,,,,,,,,
2019-10-31 04:00:00,9102.15,9116.67,166462.385,5557,-1.066541e+05,NaN,NaN,NaN,0,NaN,...,0.000000,1,NaN,0,0,NaN,-1,NaN,NaN,NaN
2019-10-31 05:00:00,9084.35,9180.61,167313.515,5594,1.754411e+04,NaN,NaN,NaN,0,NaN,...,0.000000,1,63.94,0,0,NaN,-1,NaN,NaN,NaN
2019-10-31 06:00:00,9167.46,9206.14,173418.026,5824,-7.197801e+04,NaN,NaN,NaN,0,NaN,...,0.000000,1,25.53,0,0,NaN,-1,NaN,NaN,NaN
2019-10-31 07:00:00,9120.50,9123.05,162489.166,5487,-7.221316e+04,NaN,NaN,NaN,0,NaN,...,0.000000,1,83.09,0,0,NaN,-1,NaN,NaN,NaN
2019-10-31 08:00:00,9098.24,9135.55,164301.111,7416,-3.910646e+04,NaN,NaN,NaN,0,NaN,...,0.000000,1,12.50,0,0,NaN,-1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-04-02 23:00:00,28150.00,28350.00,5663.442,4488,1.202339e+08,-3294.024327,29.549959,658.291788,1,-248.750000,...,0.000450,-1,182.40,1,1,-0.000017,1,0.344622,0.898973,1.049276
2023-04-03 00:00:00,28171.80,28350.00,4036.373,3223,1.202331e+08,-2911.328109,29.663979,614.370946,1,-207.522647,...,0.000225,-1,3.10,1,0,-0.001348,1,0.354245,0.909472,1.028449
2023-04-03 01:00:00,28177.80,28500.00,6229.230,6454,1.202328e+08,-2559.295159,31.901050,1235.787307,0,-212.568235,...,0.000112,-1,665.30,0,1,-0.002811,-1,0.322332,0.780588,0.977868
2023-04-03 02:00:00,27930.80,28100.00,4688.719,7120,1.202347e+08,-1608.361347,33.978331,1147.516785,0,-230.580882,...,0.000056,-1,400.00,0,1,-0.004320,-1,0.297696,0.882255,1.062963
2023-04-03 03:00:00,27978.00,28096.00,3605.393,4386,1.202350e+08,-973.481319,35.907234,1065.551300,0,-246.380882,...,0.000028,-1,19.70,1,0,-0.005897,-1,0.302853,0.920601,1.055379

In [66]:
relevant_indicators2 = relevant_indicators.iloc[100:].dropna(axis=1, how="any")
relevant_indicators2

,Open,High,Volume,Number of Trades,AD,ADOSC_3_10,ADX_14,DMN_14,AMATe_LR_8_21_2,AO_5_34,...,STC_10_12_26_0.5,SUPERTd_7_3.0,THERMO_20_2_0.5,THERMOl_20_2_0.5,THERMOs_20_2_0.5,TRIX_30_9,TTM_TRND_6,VHF_28,VTXP_14,VTXM_14
Date,,,,,,,,,,,,,,,,,,,,,
2019-11-04 08:00:00,9178.88,9194.43,420731.514,19263,-2.222696e+05,-51530.244728,26.954909,151.382001,1,-41.669971,...,7.000000e-08,-1,13.77,1,1,-0.006305,1,0.272415,1.022436,0.951286
2019-11-04 09:00:00,9154.96,9175.12,397521.138,17998,9.632658e+04,22925.659183,26.016902,140.569001,1,-31.982265,...,4.000000e-08,-1,19.31,1,1,-0.007146,1,0.260771,1.026755,0.997989
2019-11-04 10:00:00,9172.94,9218.02,355638.057,21889,1.760702e+05,76673.700612,24.450129,130.528358,1,-17.485294,...,2.000000e-08,-1,42.90,1,1,-0.007793,1,0.205378,1.054805,0.912747
2019-11-04 11:00:00,9199.72,9272.33,359818.123,16221,4.171685e+05,168404.314607,24.209164,121.204904,1,1.136824,...,1.000000e-08,-1,54.31,1,1,-0.008097,1,0.231616,1.198027,0.840386
2019-11-04 12:00:00,9260.20,9280.19,386134.717,17653,1.349505e+05,100824.332807,24.136936,112.547411,1,18.595971,...,0.000000e+00,-1,30.43,1,1,-0.008186,1,0.229875,1.137810,0.894363
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-04-02 23:00:00,28150.00,28350.00,5663.442,4488,1.202339e+08,-3294.024327,29.549959,658.291788,1,-248.750000,...,4.497200e-04,-1,182.40,1,1,-0.000017,1,0.344622,0.898973,1.049276
2023-04-03 00:00:00,28171.80,28350.00,4036.373,3223,1.202331e+08,-2911.328109,29.663979,614.370946,1,-207.522647,...,2.248600e-04,-1,3.10,1,0,-0.001348,1,0.354245,0.909472,1.028449
2023-04-03 01:00:00,28177.80,28500.00,6229.230,6454,1.202328e+08,-2559.295159,31.901050,1235.787307,0,-212.568235,...,1.124300e-04,-1,665.30,0,1,-0.002811,-1,0.322332,0.780588,0.977868
2023-04-03 02:00:00,27930.80,28100.00,4688.719,7120,1.202347e+08,-1608.361347,33.978331,1147.516785,0,-230.580882,...,5.622000e-05,-1,400.00,0,1,-0.004320,-1,0.297696,0.882255,1.062963
2023-04-03 03:00:00,27978.00,28096.00,3605.393,4386,1.202350e+08,-973.481319,35.907234,1065.551300,0,-246.380882,...,2.811000e-05,-1,19.70,1,0,-0.005897,-1,0.302853,0.920601,1.055379

In [34]:
df = pd.DataFrame({
    'A': [1, 0, np.nan, np.nan],
    'B': [5, np.nan, np.nan, 8],
    'C': [9, 10, 11, 12],
    'D': [13, 14, 10, 16]
})
df.corr()

     A    B         C         D
A  1.0  NaN -1.000000 -1.000000
B  NaN  1.0  1.000000  1.000000
C -1.0  1.0  1.000000  0.258199
D -1.0  1.0  0.258199  1.000000

In [64]:
from sklearn.feature_selection import f_classif

X = relevant_indicators2
y = info["Target"].iloc[100:]
# Calcula la puntuación F y los p-values para cada característica
f_scores, p_values = f_classif(X, y)

# Crea un DataFrame con las puntuaciones F y los p-values
feature_scores = pd.DataFrame({'Feature': X.columns, 'F_Score': f_scores, 'P_Value': p_values})

# Selecciona características con p-values significativos (por ejemplo, p < 0.05)
significant_features = feature_scores[feature_scores['P_Value'] < 0.05]

# Puedes usar 'significant_features' para seleccionar las características importantes

/home/mauricio/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py:112: UserWarning: Features [ 28  56  57  58  62  77 107] are constant.
  warnings.warn("Features %s are constant." % constant_features_idx, UserWarning)
/home/mauricio/anaconda3/lib/python3.9/site-packages/sklearn/feature_selection/_univariate_selection.py:113: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw

In [65]:
significant_features

             Feature      F_Score        P_Value
0               Open     4.936633   2.630066e-02
5         ADOSC_3_10    78.821961   7.167880e-19
8    AMATe_LR_8_21_2   754.078860  5.660055e-164
10         AOBV_LR_2  2202.851797   0.000000e+00
11         APO_12_26     4.580991   3.233657e-02
..               ...          ...            ...
104          SKEW_30    53.616329   2.498696e-13
105      SMIo_5_20_5  1910.784774   0.000000e+00
111    SUPERTd_7_3.0    28.744079   8.321378e-08
116       TTM_TRND_6  3878.096045   0.000000e+00
118          VTXP_14     5.203220   2.255209e-02

[82 rows x 3 columns]