In [5]:
from futures_trader import FuturesTrader

In [6]:
ft = FuturesTrader(
        pair="BTCUSDT",
        heartbeat_url="",
        heartbeat_period=300,
        testnet=True,
        verbose=True
    )

In [3]:
ft.quote

'USDT'

In [3]:
print("POSITION: ", ft.get_position())
print("OPEN BASE: ", ft.get_open_base())
print("current balance: ", ft.get_current_balance())
print("available balance: ", ft.get_available_balance())
print("current leverage: ", ft.get_current_leverage())
print("liquidation price: ", ft.get_liquidation_price())
print("entry price: ", ft.get_entry_price())

POSITION:  Position.NEUTRAL
OPEN BASE:  0.0
current balance:  14997.84894972
available balance:  3001.24894972
current leverage:  10
liquidation price:  0.0
entry price:  0.0

In [5]:
ft.change_leverage(new_leverage=10)

10

In [4]:
ft.get_most_recent_data(
    num_candles=10,
    interval="1m"
)
ft.data

,Open,High,Low,Close,Volume,Quote Asset Volume,Number of Trades,Taker Buy Base Asset Volume,Taker Buy Quote Asset Volume,Complete
Date,,,,,,,,,,
2024-01-23 23:15:00,39872.0,40357.3,39870.9,39870.9,103.338,4.140435e+06,37,41.956,1.692874e+06,True
2024-01-23 23:16:00,40096.5,40334.0,39870.9,40334.0,86.556,3.471907e+06,35,44.234,1.783998e+06,True
2024-01-23 23:17:00,39870.9,40334.0,39870.9,40334.0,70.508,2.828737e+06,33,37.879,1.527782e+06,True
2024-01-23 23:18:00,40334.0,40357.3,39870.9,40334.0,88.438,3.545263e+06,34,40.220,1.622751e+06,True
2024-01-23 23:19:00,40350.7,40357.4,39872.0,40357.4,15.081,6.075307e+05,25,9.537,3.848787e+05,True
2024-01-23 23:20:00,40238.6,40357.4,39872.0,40357.4,22.991,9.245064e+05,37,13.379,5.399409e+05,True
2024-01-23 23:21:00,40357.4,40357.4,39872.0,39872.0,45.052,1.812063e+06,41,32.621,1.316404e+06,True
2024-01-23 23:22:00,40357.4,40357.5,39872.0,39872.0,27.962,1.123042e+06,38,16.879,6.811397e+05,True
2024-01-23 23:23:00,39938.7,40350.4,39872.0,40350.0,13.902,5.593420e+05,36,10.403,4.197493e+05,True
2024-01-23 23:24:00,39938.7,40350.0,39870.9,40350.0,28.459,1.146059e+06,42,23.905,9.644628e+05,False

In [7]:
ft.go_long(
    quote=150,
    price=40000,
    use_wallet_prc = False,
    order_type = "MARKET",
    reduceOnly = False,
)

In [9]:
ft.go_neutral(
    order_type = "MARKET",
    prc = 100,
    price = 40800
)

In [3]:
ft.go_stop_market(
    when_prc_reaches = 80.0
)

0.0
40370.0
8074.0

In [16]:
ft.close_all_stop_market()

,orderId,symbol,status,clientOrderId,price,avgPrice,origQty,executedQty,cumQuote,timeInForce,...,positionSide,stopPrice,workingType,priceProtect,origType,priceMatch,selfTradePreventionMode,goodTillDate,time,updateTime
0,3665059846,BTCUSDT,NEW,60fuqbCLmAeX3GqkJG1rYW,38000.00,0.00000,3.157,0.000,0.00000,GTC,...,BOTH,0.00,CONTRACT_PRICE,False,LIMIT,NONE,NONE,0,1706054396855,1706054396855

In [9]:
ft.get_order(ft.history["last_pos_open"])

{'orderId': 3665083499,
 'symbol': 'BTCUSDT',
 'status': 'FILLED',
 'clientOrderId': 'y5RQX9tdJIV6g8Tir2rEZO',
 'price': '0.00',
 'avgPrice': '40371.10000',
 'origQty': '0.004',
 'executedQty': '0.004',
 'cumQuote': '161.48440',
 'timeInForce': 'GTC',
 'type': 'MARKET',
 'reduceOnly': False,
 'closePosition': False,
 'side': 'BUY',
 'positionSide': 'BOTH',
 'stopPrice': '0.00',
 'workingType': 'CONTRACT_PRICE',
 'priceProtect': False,
 'origType': 'MARKET',
 'priceMatch': 'NONE',
 'selfTradePreventionMode': 'NONE',
 'goodTillDate': 0,
 'time': 1706056369960,
 'updateTime': 1706056369963}

In [14]:
import pandas as pd
pos = pd.DataFrame(ft.client.futures_account()['positions'])
pos [
    pos["symbol"] == "BTCUSDT"
]

,symbol,initialMargin,maintMargin,unrealizedProfit,positionInitialMargin,openOrderInitialMargin,leverage,isolated,entryPrice,breakEvenPrice,maxNotional,positionSide,positionAmt,notional,isolatedWallet,updateTime,bidNotional,askNotional
178,BTCUSDT,16.02604820,0.64104193,-1.22391803,16.02604820,0.00000000,10,False,40371.1,40387.24844,40000000.00000000,BOTH,0.004,160.26048197,0.00000000,1706056369963,0.00000000,0.00000000